#if !defined(AFX_PICTURE1_H__E9C80BE5_3E4E_412C_BEC1_FB1B2D5707D8__INCLUDED_)
#define AFX_PICTURE1_H__E9C80BE5_3E4E_412C_BEC1_FB1B2D5707D8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPicture1 wrapper class

class CPicture1 : public COleDispatchDriver
{
public:
	CPicture1() {}		// Calls COleDispatchDriver default constructor
	CPicture1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPicture1(const CPicture1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetHandle();
	long GetHPal();
	void SetHPal(long);
	short GetType();
	long GetWidth();
	long GetHeight();

// Operations
public:
	// method 'Render' not emitted because of invalid return type or parameter type
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PICTURE1_H__E9C80BE5_3E4E_412C_BEC1_FB1B2D5707D8__INCLUDED_)
