#if !defined(AFX_ROWCURSOR1_H__D4542828_4FF2_4869_A1F2_FCB377A164AE__INCLUDED_)
#define AFX_ROWCURSOR1_H__D4542828_4FF2_4869_A1F2_FCB377A164AE__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRowCursor1 wrapper class

class CRowCursor1 : public COleDispatchDriver
{
public:
	CRowCursor1() {}		// Calls COleDispatchDriver default constructor
	CRowCursor1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRowCursor1(const CRowCursor1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ROWCURSOR1_H__D4542828_4FF2_4869_A1F2_FCB377A164AE__INCLUDED_)
